### ISSUE TITLE
Add a Denis Tag 

### ISSUE THREAD

**Issue by loispostula** [UrLab/DocHub#100]
For all the quality notes, to make it easier to find them

**Comment by titouanc** [comment]
C'est fait. Pour info, voici la liste des tags à l'heure actuelle:
![image](https://cloud.githubusercontent.com/assets/245617/17833808/2c015ef2-6728-11e6-8175-6dbf73a23dad.png)

**Comment by Mixone-FinallyHere** [comment]
je comprends pas
denis veut dire quality notes?
