### ISSUE TITLE
[New Functionality] Folder-like organisation of files in course. 

### ISSUE THREAD

**Issue by Mixone-FinallyHere** [UrLab/DocHub#101]
# Idea

Now that dochub has been running for quite some time, and the number of documents in some courses is starting to become large, it might be good to have a folder-like system inside each course page.
# What I see it being:

A system that, rather than remove old functionalities, will add upon the existing ones. Files should be able to be kept outside of folders (or addition of a folder "Autres"). 

Folders that can be either created by an admin or a user and that anyone can add to.

They can be expanded or closed so that finding a file is simpler.

Possibility of upon uploading a file choosing to which directory it has to go, if it has to go to one.
# What it would look like

![coursepageold](https://cloud.githubusercontent.com/assets/11949750/19150858/a17c7674-8bc9-11e6-9a82-5dd2eaabb865.png)
# What would be required
- Some additions to upload code to take into account folders. 
- Database column for folder location (maybe only). 
- A bit of graphical tinkering with javascript and/or css to show them, hide them on click event.

I think that more or less covers it all.

Please do not hesitate to tell me if it is a stupid idea. It just seems to me that in some course pages the file load is so large it is starting to become more cumbersome than helpful.

**Comment by bil-elmoussaoui** [comment]
Is anyone working on this at the moment? if not, i can see what can i do this weekend

**Comment by PierreGe** [comment]
Yeah, I do believe that nobody is, you're more than welcome to give it a go ! 👍

**Comment by C4ptainCrunch** [comment]
Hum, i'm not convinced that it's something we need actually. It might clutter the interface a lot and make the navigation less easy (especially if it's done like in the screenshot)

**Comment by Mixone-FinallyHere** [comment]
The screenschot is just edited with paint so not really like it would look like with proper css and js
