### ISSUE TITLE
"Ajouter" une discussion à un document

### ISSUE THREAD

**Issue by detobel36** [UrLab/DocHub#113]
Impossible (pour ma part en tout cas) de créer une discussion en lien avec une page d'un document.       
Testé ici par exemple: https://dochub.be/documents/61339#page-4      
Screen: ![capt](https://cloud.githubusercontent.com/assets/5373615/21563196/ae257eea-ce7f-11e6-93e1-54bedabd8d28.png)
```
3party.a4ef33add2b4.js:9860

Uncaught TypeError: o.on(...).trigger is not a function
    at Object.open (3party.a4ef33add2b4.js:9860)
    at HTMLAnchorElement.<anonymous> (3party.a4ef33add2b4.js:9860)
    at HTMLDocument.dispatch (3party.a4ef33add2b4.js:4742)
    at HTMLDocument.elemData.handle (3party.a4ef33add2b4.js:4554)
open @ 3party.a4ef33add2b4.js:9860
(anonymous) @ 3party.a4ef33add2b4.js:9860
dispatch @ 3party.a4ef33add2b4.js:4742
elemData.handle @ 3party.a4ef33add2b4.js:4554
```

**Comment by Mixone-FinallyHere** [comment]
Ceci vient lors du 3rd party de JQuery  requestAnimationFrame donc

1. Faudrait voir avec le 3rd party
2. On pourrait changer la ligne de erreur avec aide de [ici](http://stackoverflow.com/questions/18693463/jquery-triggerchange-not-working)

**Comment by Mixone-FinallyHere** [comment]
Aussi ici ça a l'air de un solution beaucoup plus exacte:

http://stackoverflow.com/questions/34750123/uncaught-typeerror-modal-on-trigger-is-not-a-function-when-using-zurb-foun

**Comment by C4ptainCrunch** [comment]
Ca devrait être fixé dans la prochaine version, je ferme
