### ISSUE TITLE
Coveralls update

### ISSUE THREAD

**Issue by Mixone-FinallyHere** [UrLab/DocHub#147]
Coveralls needs to be updated, someone has to set it to ON on coveralls site.

Then README badge has to be updated from beta402 to DocHub

**Comment by Mixone-FinallyHere** [comment]
@C4ptainCrunch or @titouanc have to be the ones to do it I think

**Comment by C4ptainCrunch** [comment]
I removed coveralls for the moment as nobody uses it. Also it might not even be the state of the art anymore.
