### ISSUE TITLE
La page de l'affichage du document n'est pas responsive

### ISSUE THREAD

**Issue by Ouroborossignol** [UrLab/DocHub#150]
Une partie du document n'est pas visible si l'écran n'est pas adapté.

![screenshot_2019-02-19 infofond](https://user-images.githubusercontent.com/32895828/53041629-bf38aa00-3484-11e9-91c6-e9e70fb07d58.png)

**Comment by Mixone-FinallyHere** [comment]
## Possible (untested) solution

Using Bootstrap css embedded responsive class it should be able to handle that on its own doing:
```html
<div class='embed-responsive'>
    <object data='URL.pdf' type='application/pdf' width='100%' height='100%'></object>
</div>
```
Or
```html
<div class='embed-responsive'>
    <!-- place span code of viewer.html here -->
</div>
```

**Comment by C4ptainCrunch** [comment]
fixed on `main` (not yet deployed)
