### ISSUE TITLE
Y a des énormes espaces entre deux pages

### ISSUE THREAD

**Issue by Mortinat** [UrLab/DocHub#156]
y a un petit soucis sur ce documents il y a d'énormes espaces entre les pages du documents (durant 4-5 page) 
![2019-10-09-184122_1366x768_scrot](https://user-images.githubusercontent.com/43477020/66501866-bc420680-eab3-11e9-85a2-6d1a2d77cbfa.png)

https://dochub.be/documents/458

**Comment by Mortinat** [comment]
![2019-11-12-144134_1366x768_scrot](https://user-images.githubusercontent.com/43477020/68783063-50af0400-0632-11ea-904b-841c465cd241.png)
meme soucis mais avec les petit cadres rouges en plus

**Comment by mdirksen** [comment]
problème dû aux hyperliens des sommaires ?

**Comment by C4ptainCrunch** [comment]
fixed on `main` (not yet deployed)
