### ISSUE TITLE
Page d'acceuil à refaire

### ISSUE THREAD

**Issue by Bruno-brsy** [UrLab/DocHub#200]
* Doit rajouter sur la page d’accueil de dochub qu'on est pas officiel et noter les cannaux officiels
* Ce serait sympa de nous mettre + en avant sur la page d'accueil de dochub (avec nos logos + gros que les actuels et comme quoi dochub est fait par les étudiants entre étudiants)

**Comment by C4ptainCrunch** [comment]
Already tracked in #165 and #199
