### ISSUE TITLE
Formulaire de contact

### ISSUE THREAD

**Issue by C4ptainCrunch** [UrLab/DocHub#63]
Il faudrait un moyen facile de contecter les admins/dev pour signaler un bug, poser une question ou proposer une amélioration sans devoir passer par GitHub

**Comment by titouanc** [comment]
Un workaround rapide à mettre en place serait de créer un "faux cours" DocHub, qui permettrait de placer des discussions.

**Comment by Mixone-FinallyHere** [comment]
Possible aide:
https://github.com/schneidmaster/gitreports.com

**Comment by C4ptainCrunch** [comment]
On a drift, plus besoin
