### ISSUE TITLE
Very slow treatment of docs after site was down on the 26/04/16

### ISSUE THREAD

**Issue by Mixone-FinallyHere** [UrLab/DocHub#88]
Le site donne ceci depuis au moins 24 heures:

![dochubfail](https://cloud.githubusercontent.com/assets/11949750/14860452/32c5306c-0ca9-11e6-96fb-2b5babe0a14c.PNG)

**Comment by C4ptainCrunch** [comment]
Problème connu, on fixe ça bientôt ;)

**Comment by Mixone-FinallyHere** [comment]
Oups, deso pour le harcelement alors haha
