### ISSUE TITLE
Erreur 500 lorsqu'un fichier n'a pas d'extension

### ISSUE THREAD

**Issue by titouanc** [UrLab/DocHub#95]
Lorsqu'on upload un document dont le nom de fichier original n'a pas d'extension, une erreur 500 se produit.
Il devrait être possible d'inférer le type de fichier, par exemple en utilisant `file` ou https://pypi.python.org/pypi/filemagic

**Comment by Mixone-FinallyHere** [comment]
ceci pourrait se faire avant le upload?
ou au moins avertir lors de la selection du fichier?
